# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "John Snell"                                # Your name
  description: ""   # A brief slogan (optional)
  image: img/John_Snell.png
  
  favicon: img/John_Snell.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/John_Snell.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: Publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: Blog/index.qmd
    
    # your social media handles
    right:
#      - icon: folder-symlink
#        href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
#      - icon: twitter
#        href: https://twitter.com/MarvinSchmittML
#      - icon: linkedin
#        href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: envelope
        aria-label: email
        href: "mailto:jcs296@case.edu"

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - slate
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true